//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileBook.Resource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileBook.Resource.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By date added to the database.
        /// </summary>
        internal static string by_date_added_to_the_database {
            get {
                return ResourceManager.GetString("by_date_added_to_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By the name.
        /// </summary>
        internal static string by_the_name {
            get {
                return ResourceManager.GetString("by_the_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By the Nick Name.
        /// </summary>
        internal static string by_the_nick_name {
            get {
                return ResourceManager.GetString("by_the_nick_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change the language:.
        /// </summary>
        internal static string change_the_language {
            get {
                return ResourceManager.GetString("change_the_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Password .
        /// </summary>
        internal static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на German.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable dark theme .
        /// </summary>
        internal static string enable_dark_theme {
            get {
                return ResourceManager.GetString("enable_dark_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на French.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name and NickName fields must be filled!.
        /// </summary>
        internal static string information_is_missing_in_the_fields_name_and_nick_name {
            get {
                return ResourceManager.GetString("information_is_missing_in_the_fields_name_and_nick_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid data entered.
        /// </summary>
        internal static string invalid_data_entered {
            get {
                return ResourceManager.GetString("invalid_data_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid login or password!.
        /// </summary>
        internal static string invalid_login_or_password {
            get {
                return ResourceManager.GetString("invalid_login_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NickName.
        /// </summary>
        internal static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No profiles added.
        /// </summary>
        internal static string no_profiles_added {
            get {
                return ResourceManager.GetString("no_profiles_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password and login do not exist in the database!.
        /// </summary>
        internal static string password_or_user_name_does_not_exist {
            get {
                return ResourceManager.GetString("password_or_user_name_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick at gallery.
        /// </summary>
        internal static string pick_at_gallery {
            get {
                return ResourceManager.GetString("pick_at_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polish.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please pick a photo.
        /// </summary>
        internal static string please_pick_a_photo {
            get {
                return ResourceManager.GetString("please_pick_a_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password must be at least 8 and no more than 16 characters and contain at least one uppercase letter, one lowercase letter and one number.
        /// </summary>
        internal static string requirements_for_password_and_confirm_password {
            get {
                return ResourceManager.GetString("requirements_for_password_and_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login must be at least 4 and no more than 16 characters and not start with numbers!.
        /// </summary>
        internal static string requirements_to_login {
            get {
                return ResourceManager.GetString("requirements_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password must be at least 8 and no more than 16 characters and contain at least one uppercase letter, one lowercase letter and one number!.
        /// </summary>
        internal static string requirements_to_password {
            get {
                return ResourceManager.GetString("requirements_to_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select sorting option:.
        /// </summary>
        internal static string select_sorting_option {
            get {
                return ResourceManager.GetString("select_sorting_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SIGN UP.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Take photo with camera.
        /// </summary>
        internal static string take_photo_with_camera {
            get {
                return ResourceManager.GetString("take_photo_with_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This login is already taken!.
        /// </summary>
        internal static string this_login_is_already_taken {
            get {
                return ResourceManager.GetString("this_login_is_already_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Profile.
        /// </summary>
        internal static string title_add_profile {
            get {
                return ResourceManager.GetString("title_add_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main List.
        /// </summary>
        internal static string title_main_list {
            get {
                return ResourceManager.GetString("title_main_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string title_settings {
            get {
                return ResourceManager.GetString("title_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SignIn.
        /// </summary>
        internal static string title_sign_in {
            get {
                return ResourceManager.GetString("title_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        internal static string title_sign_up {
            get {
                return ResourceManager.GetString("title_sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You really want to delete this profile?.
        /// </summary>
        internal static string you_really_want_to_delete_this_profile {
            get {
                return ResourceManager.GetString("you_really_want_to_delete_this_profile", resourceCulture);
            }
        }
    }
}
